import { useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { BookOpenCheck, CalendarClock, Check, ChevronDown, CircleAlert, Code2, GraduationCap, Hammer, ListChecks, NotebookPen, Target, Trophy } from 'lucide-react'
import { db } from '../db'
import { percent } from '../metrics'
import type { RoadmapWeek } from '../types'

export function PremiumGate(){
  const subjects=useLiveQuery(()=>db.gate.toArray(),[])||[]
  const backlog=useLiveQuery(()=>db.backlog.toArray(),[])||[]
  const [expanded,setExpanded]=useState<number>()
  const probability=subjects.find(s=>s.name==='Probability and Statistics')
  const sprintDone=backlog.reduce((sum,d)=>sum+[d.pending,d.current,d.dpp,d.revision,d.test].filter(Boolean).length,0)
  const sprintTotal=backlog.length*5
  const firstOpen=backlog.find(day=>![day.pending,day.current,day.dpp,day.revision].every(Boolean))
  const remaining=backlog.filter(day=>!day.pending).length
  const chart=subjects.map(s=>({name:s.name.replace('Computer Organization and Architecture','COA').replace('Probability and Statistics','Probability'),progress:percent(s.lectures,s.totalLectures)}))
  const toggle=(id:number,field:'pending'|'current'|'dpp'|'revision'|'test',value:boolean)=>db.backlog.update(id,{[field]:value})
  return <div className="page academic-page"><header className="premium-hero"><div><span className="eyebrow">GATE COMMAND CENTER</span><h1>Clear the backlog. Keep the current class.</h1><p>Every lecture, DPP, revision cycle, PYQ and test—visible in one system.</p></div><div className="countdown-card"><span><CalendarClock/></span><div><small>Probability sprint</small><b>{remaining} pending lectures</b><em>{firstOpen?`Continue Day ${firstOpen.day}`:'Sprint complete'}</em></div></div></header>
    <div className="premium-metrics-grid"><article className="premium-metric violet"><span className="metric-icon"><GraduationCap/></span><div><small>Lectures</small><strong>{subjects.reduce((a,s)=>a+s.lectures,0)}/{subjects.reduce((a,s)=>a+s.totalLectures,0)}</strong><span>Across 16 subjects</span></div></article><article className="premium-metric amber"><span className="metric-icon"><CircleAlert/></span><div><small>Probability backlog</small><strong>{remaining}</strong><span>One pending lecture daily</span></div></article><article className="premium-metric blue"><span className="metric-icon"><ListChecks/></span><div><small>PYQs solved</small><strong>{subjects.reduce((a,s)=>a+s.pyqs,0)}</strong><span>All subjects</span></div></article><article className="premium-metric pink"><span className="metric-icon"><Trophy/></span><div><small>Tests tracked</small><strong>{subjects.reduce((a,s)=>a+s.tests,0)}</strong><span>{probability?.scores||'Add the first score'}</span></div></article></div>
    <div className="academic-top-grid"><section className="premium-panel"><div className="premium-panel-head"><div><span className="eyebrow">SUBJECT PROGRESS</span><h2>Lecture completion</h2></div><span className="score-chip">{percent(subjects.reduce((a,s)=>a+s.lectures,0),subjects.reduce((a,s)=>a+s.totalLectures,0))}% overall</span></div><div className="premium-chart gate-chart"><ResponsiveContainer><BarChart data={chart}><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey="name" hide/><YAxis domain={[0,100]} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="progress" fill="#8b7cf6" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></section><section className="probability-focus"><span className="eyebrow">TODAY’S PROBABILITY PAIR</span><h2>Day {firstOpen?.day||11}</h2><p>Keep the backlog and current course moving together.</p><div><span><b>01</b>Pending lecture</span><span><b>02</b>Current lecture</span><span><b>03</b>DPP + revision</span></div><strong>{percent(sprintDone,sprintTotal)}% sprint completion</strong><div className="habit-progress"><span style={{width:`${percent(sprintDone,sprintTotal)}%`}}/></div></section></div>
    <section className="premium-panel sprint-table"><div className="premium-panel-head"><div><span className="eyebrow">11-DAY BACKLOG RECOVERY</span><h2>Probability & Statistics</h2></div><span className="score-chip">{remaining} days remaining</span></div><div className="sprint-grid"><div className="sprint-head"><span>Day</span><span>Pending</span><span>Current</span><span>DPP</span><span>Revision</span><span>Test</span><span>Notes</span></div>{backlog.map(day=><div className="sprint-row" key={day.id}><b>Day {day.day}</b>{(['pending','current','dpp','revision','test'] as const).map(field=><button key={field} className={day[field]?'checked':''} onClick={()=>toggle(day.id!,field,!day[field])}>{day[field]?<Check size={14}/>:null}</button>)}<input value={day.notes} onChange={e=>db.backlog.update(day.id!,{notes:e.target.value})} placeholder="Doubts or score…"/></div>)}</div></section>
    <div className="subject-premium-grid">{subjects.map(subject=>{const progress=percent(subject.lectures,subject.totalLectures);return <article className="premium-subject" key={subject.id}><button className="subject-head" onClick={()=>setExpanded(expanded===subject.id?undefined:subject.id)}><span><GraduationCap/></span><div><small>{progress}% COMPLETE</small><h3>{subject.name}</h3></div><ChevronDown className={expanded===subject.id?'open':''}/></button><div className="habit-progress"><span style={{width:`${progress}%`}}/></div><div className="subject-mini-stats"><span><b>{subject.lectures}/{subject.totalLectures}</b><small>lectures</small></span><span><b>{subject.dppPending}</b><small>DPP pending</small></span><span><b>{subject.pyqs}</b><small>PYQs</small></span><span><b>{subject.tests}</b><small>tests</small></span></div>{expanded===subject.id&&<div className="subject-editor"><label>Lectures<input type="number" value={subject.lectures} onChange={e=>db.gate.update(subject.id!,{lectures:+e.target.value})}/></label><label>Total<input type="number" value={subject.totalLectures} onChange={e=>db.gate.update(subject.id!,{totalLectures:+e.target.value})}/></label><label>DPP done<input type="number" value={subject.dpp} onChange={e=>db.gate.update(subject.id!,{dpp:+e.target.value})}/></label><label>DPP pending<input type="number" value={subject.dppPending} onChange={e=>db.gate.update(subject.id!,{dppPending:+e.target.value})}/></label><label>PYQs<input type="number" value={subject.pyqs} onChange={e=>db.gate.update(subject.id!,{pyqs:+e.target.value})}/></label><label>Tests<input type="number" value={subject.tests} onChange={e=>db.gate.update(subject.id!,{tests:+e.target.value})}/></label><label className="wide">Scores<input value={subject.scores} onChange={e=>db.gate.update(subject.id!,{scores:e.target.value})}/></label><label className="wide">Notes<textarea value={subject.notes} onChange={e=>db.gate.update(subject.id!,{notes:e.target.value})}/></label></div>}</article>})}</div>
  </div>
}

export function PremiumSemester(){
  const subjects=useLiveQuery(()=>db.college.toArray(),[])||[]
  const [target,setTarget]=useState(8.5)
  const totalCredits=subjects.reduce((a,s)=>a+s.credits,0)
  const predicted=subjects.reduce((a,s)=>a+(s.gradePoint??Math.min(10,Math.max(4,Math.round((s.internalMarks/50)*4+6))))*s.credits,0)/Math.max(1,totalCredits)
  const attendance=Math.round(subjects.reduce((a,s)=>a+s.attendance,0)/Math.max(1,subjects.length))
  const assignments=subjects.reduce((a,s)=>a+s.assignments,0)
  return <div className="page academic-page"><header className="premium-hero"><div><span className="eyebrow">SEMESTER 5 OPERATING SYSTEM</span><h1>Stay ahead before the deadline arrives.</h1><p>Attendance, assignments, labs, exams and a transparent CGPA forecast.</p></div><div className="cgpa-hero"><small>PREDICTED SGPA</small><b>{predicted.toFixed(2)}</b><span>Target {target.toFixed(1)}</span></div></header>
    <div className="premium-metrics-grid"><article className="premium-metric blue"><span className="metric-icon"><BookOpenCheck/></span><div><small>Subjects</small><strong>{subjects.length}</strong><span>{totalCredits} total credits</span></div></article><article className="premium-metric green"><span className="metric-icon"><Check/></span><div><small>Attendance</small><strong>{attendance}%</strong><span>{attendance>=75?'On track':'Needs attention'}</span></div></article><article className="premium-metric amber"><span className="metric-icon"><NotebookPen/></span><div><small>Assignments</small><strong>{assignments}</strong><span>Tracked submissions</span></div></article><article className="premium-metric pink"><span className="metric-icon"><Target/></span><div><small>SGPA target</small><strong>{target.toFixed(1)}</strong><span>Adjust below</span></div></article></div>
    <section className="premium-panel cgpa-predictor"><div><span className="eyebrow">CGPA PREDICTOR</span><h2>Model the semester outcome</h2><p>Enter the expected grade point for each subject. Forge weights it by credits.</p></div><label>Target SGPA <input type="range" min="6" max="10" step=".1" value={target} onChange={e=>setTarget(+e.target.value)}/><b>{target.toFixed(1)}</b></label><div className={`prediction-gap ${predicted>=target?'positive':''}`}><span>{predicted>=target?<Trophy/>:<Target/>}</span><div><small>{predicted>=target?'ABOVE TARGET':'GAP TO TARGET'}</small><b>{Math.abs(predicted-target).toFixed(2)} points</b></div></div></section>
    <div className="semester-grid">{subjects.map(subject=><article className="semester-card" key={subject.id}><header><span><BookOpenCheck/></span><div><small>{subject.credits} CREDITS</small><h2>{subject.name}</h2></div><em>{subject.progress}%</em></header><div className="habit-progress"><span style={{width:`${subject.progress}%`}}/></div><div className="semester-fields"><label>Attendance<input type="number" min="0" max="100" value={subject.attendance} onChange={e=>db.college.update(subject.id!,{attendance:+e.target.value})}/><span>%</span></label><label>Assignments<input type="number" min="0" value={subject.assignments} onChange={e=>db.college.update(subject.id!,{assignments:+e.target.value})}/></label><label>Labs<input type="number" min="0" value={subject.labs||0} onChange={e=>db.college.update(subject.id!,{labs:+e.target.value})}/></label><label>Internal marks<input type="number" min="0" max="50" value={subject.internalMarks} onChange={e=>db.college.update(subject.id!,{internalMarks:+e.target.value})}/><span>/50</span></label><label>Grade point<input type="number" min="0" max="10" value={subject.gradePoint||0} onChange={e=>db.college.update(subject.id!,{gradePoint:+e.target.value})}/><span>/10</span></label><label>Exam<input type="date" value={subject.examDate} onChange={e=>db.college.update(subject.id!,{examDate:e.target.value})}/></label></div><textarea value={subject.notes} onChange={e=>db.college.update(subject.id!,{notes:e.target.value})} placeholder="Assignments, lab work, exam topics…"/></article>)}</div>
  </div>
}

const monthNames=['Python & Git','Data & Pandas','NLP & Embeddings','Generative AI','RAG Systems','Machine Learning','Reliable RAG','Agents & Deployment','Capstone & Portfolio']
export function PremiumRoadmap(){
  const weeks=useLiveQuery(()=>db.roadmap.toArray(),[])||[]
  const [month,setMonth]=useState(1)
  const done=weeks.reduce((a,w)=>a+w.completedTopics.length+(w.buildDone?1:0),0),total=weeks.reduce((a,w)=>a+w.topics.length+1,0)
  const filtered=weeks.filter(w=>w.month===month)
  const updateTopics=(week:RoadmapWeek,topic:string,checked:boolean)=>db.roadmap.update(week.id!,{completedTopics:checked?[...week.completedTopics,topic]:week.completedTopics.filter(t=>t!==topic)})
  return <div className="page roadmap-premium"><header className="premium-hero"><div><span className="eyebrow">9-MONTH · 36-WEEK AI ENGINEER PATH</span><h1>Learn. Build. Explain. Ship.</h1><p>A sustainable progression for a busy college schedule, from Python foundations to a production capstone.</p></div><div className="roadmap-orbit"><b>{percent(done,total)}%</b><span>overall</span></div></header>
    <nav className="roadmap-months">{monthNames.map((name,index)=><button key={name} className={month===index+1?'active':''} onClick={()=>setMonth(index+1)}><span>{String(index+1).padStart(2,'0')}</span><div><small>MONTH {index+1}</small><b>{name}</b></div></button>)}</nav>
    <div className="roadmap-premium-list">{filtered.map(week=>{const weekDone=week.completedTopics.length+(week.buildDone?1:0),weekTotal=week.topics.length+1,progress=percent(weekDone,weekTotal);return <article key={week.id} className="roadmap-premium-card"><aside><span>WEEK</span><b>{week.week}</b><i className={week.status.toLowerCase().replace(' ','-')}/></aside><main><header><div><span className="eyebrow">{monthNames[week.month-1]}</span><h2>{week.title}</h2></div><select value={week.status} onChange={e=>db.roadmap.update(week.id!,{status:e.target.value as RoadmapWeek['status']})}><option>Not started</option><option>Learning</option><option>Complete</option></select></header><div className="roadmap-progress"><span style={{width:`${progress}%`}}/><b>{progress}%</b></div><section><div className="roadmap-section-title"><Code2/><b>Topics</b></div><div className="roadmap-topics">{week.topics.map(topic=><label key={topic}><input type="checkbox" checked={week.completedTopics.includes(topic)} onChange={e=>updateTopics(week,topic,e.target.checked)}/><span>{topic}</span></label>)}</div></section><div className="roadmap-detail-grid"><label><span><BookOpenCheck/> Resources</span><textarea value={week.resources||''} onChange={e=>db.roadmap.update(week.id!,{resources:e.target.value})} placeholder="Courses, docs, papers, videos…"/></label><label><span><NotebookPen/> Notes</span><textarea value={week.notes} onChange={e=>db.roadmap.update(week.id!,{notes:e.target.value})} placeholder="What clicked? What needs another pass?"/></label></div><label className={`roadmap-build ${week.buildDone?'done':''}`}><input type="checkbox" checked={week.buildDone} onChange={e=>db.roadmap.update(week.id!,{buildDone:e.target.checked})}/><Hammer/><span><small>WEEKLY SHIP</small><b>{week.build}</b></span><Check/></label><div className="roadmap-footer"><input type="url" value={week.github} onChange={e=>db.roadmap.update(week.id!,{github:e.target.value})} placeholder="GitHub or deployment URL"/><input type="date" value={week.completionDate} onChange={e=>db.roadmap.update(week.id!,{completionDate:e.target.value})}/></div></main></article>})}</div>
  </div>
}
