import type { Category, CollegeSubject, GateSubject, Habit, RoadmapWeek } from './types'
const colors=['#8b5cf6','#3b82f6','#ec4899','#10b981','#f59e0b']
const demos:[string,Category,string][]=[['Pending GATE lecture','GATE','BookOpen'],['Current GATE lecture','GATE','GraduationCap'],['DPP','GATE','FileCheck'],['GATE revision','GATE','RefreshCcw'],['Morning bus study','Bus Study','Bus'],['Evening bus revision','Bus Study','Bus'],['College assignment','College','NotebookPen'],['Python or AI learning','AI Roadmap','BrainCircuit'],['GitHub commit','GitHub','Github'],['Family time','Family','Heart'],['Sleep at least 6 hours','Health','Moon'],['Drink water','Health','Droplets'],['No unnecessary phone use','Personal','SmartphoneOff'],['Weekly review','Personal','ClipboardCheck']]
export const demoHabits:Habit[]=demos.map(([name,category,icon],i)=>({name,category,icon,description:'',schedule:name==='Weekly review'?'weekdays':'daily',weekdays:name==='Weekly review'?[0]:[0,1,2,3,4,5,6],weeklyTarget:name==='Weekly review'?1:7,startDate:category==='Bus Study'?'2026-08-03':new Date().toISOString().slice(0,10),reminder:'',color:colors[i%colors.length],archived:false,createdAt:new Date().toISOString()}))
const gateNames=['Linear Algebra','Probability and Statistics','Theory of Computation','Compiler Design','Algorithms','Computer Organization and Architecture','Operating Systems','Computer Networks','C Programming','Digital Logic','Calculus and Optimization','General Aptitude','Discrete Mathematics','Verbal Aptitude','Data Structures','DBMS']
export const gateSubjects:GateSubject[]=gateNames.map((name,i)=>({name,lectures:i===1?4:0,totalLectures:i===1?22:20,dpp:i===1?2:0,dppPending:i===1?6:0,pyqs:0,tests:0,scores:'',revision:false,notes:''}))
const collegeNames=['Advanced Java Programming','Computer Organization and Architecture','Machine Learning','Operating Systems','Gender, Popular Culture and Law','Summer Internship','GenAI','Co-Curricular Gymnasium']
export const collegeSubjects:CollegeSubject[]=collegeNames.map((name,i)=>({name,credits:i===7?1:3,attendance:0,assignments:0,internalMarks:0,examDate:'',notes:'',weeklyTarget:3,progress:0}))
const roadmap:[string,string[],string][]=[
['Python foundations',['Variables','Data types','Conditionals','Loops','Debugging'],'Calculator + number guessing game'],['Functions & collections',['Functions','Arguments','Return values','Scope','Lists','Dictionaries','Tuples','Sets'],'Marks analyzer + to-do list'],['Object-oriented Python',['Classes','Objects','Inheritance','CSV','JSON','Files','Exceptions'],'Library management system'],['Git & developer workflow',['Git','GitHub','Commit','Branch','Merge','Pull requests'],'Publish and document the first three projects'],
['APIs & command-line apps',['HTTP','REST APIs','JSON','Requests','Errors','Environment variables'],'Weather CLI app'],['Pandas foundations',['DataFrames','CSV','Excel','Filtering','Sorting','Grouping'],'Dataset explorer'],['Data cleaning & EDA',['Missing values','Duplicates','Feature engineering','Visualization'],'Data-cleaning report'],['Data portfolio sprint',['Reusable notebooks','Storytelling','README writing','GitHub hygiene'],'End-to-end analysis portfolio project'],
['Text preprocessing',['Tokenization','Stopwords','Normalization','Regex'],'Text-cleaning pipeline'],['NLP foundations',['Bag of words','TF-IDF','Classification','Evaluation'],'Text classifier'],['Embeddings',['Sentence transformers','Vector representations','Cosine similarity'],'Semantic notes search'],['NLP consolidation',['Error analysis','Experiment tracking','Documentation'],'Polished NLP mini-project'],
['LLM foundations',['Tokens','Context windows','Inference','Limitations'],'Simple chatbot'],['Prompt engineering',['Role prompting','Few-shot prompting','JSON outputs','Iteration'],'Document summarizer'],['GenAI APIs',['Responses','Errors','Streaming','Cost tracking'],'Multimodal API wrapper'],['Function calling',['Tools','Structured outputs','Validation','Tool chaining'],'Tool-using assistant'],
['RAG foundations',['Architecture','Chunking','Metadata','Ingestion'],'Document chunking pipeline'],['Vector databases',['Chroma','pgvector','Pinecone concepts','Similarity search'],'Vector search system'],['Retrieval & generation',['Context injection','Hybrid search','Reranking','Citations'],'Document Q&A bot'],['RAG frameworks',['LangChain','LlamaIndex','LangSmith','Langfuse'],'Production-style RAG app'],
['Machine-learning foundations',['Supervised learning','Unsupervised learning','Problem framing'],'ML problem definition'],['Regression & classification',['Linear regression','Logistic regression','Scikit-learn'],'Prediction model'],['Trees & ensembles',['Decision trees','Random forests','Boosting','Feature importance'],'Model comparison notebook'],['Model evaluation',['Accuracy','Precision','Recall','F1','Cross-validation','Overfitting'],'Evaluation report'],
['Advanced retrieval',['Embeddings deep dive','Reranking','Query rewriting','Fine-tuning decisions'],'RAG reranker'],['LLM evaluation',['Golden datasets','LLM-as-judge','Human review','Regression tests'],'Evaluation harness'],['RAG reliability',['Grounding','Citations','Fallbacks','Prompt injection defense'],'Hardened RAG system'],['Capstone discovery',['User problem','Requirements','Architecture','Success metrics'],'Capstone proposal and technical plan'],
['Agents',['Planning','Reasoning','Tool orchestration','When not to use agents'],'Workflow automation agent'],['Agent workflows',['State','Memory','Human approval','Retries'],'Reliable multi-step workflow'],['Production AI',['Logging','Monitoring','Docker','Safety','PII'],'Observable containerized AI service'],['Deployment',['FastAPI','Cloud deployment','Secrets','CI/CD'],'Deploy an AI application'],
['Capstone build',['Backend','Retrieval','Tools','Interface'],'Working capstone alpha'],['Capstone evaluation',['Test set','Quality metrics','Latency','Cost'],'Capstone evaluation report'],['ML workflow practice',['Preprocessing','Pipelines','Baselines','Experiment notes'],'Reproducible ML baseline'],['Model evaluation lab',['Train/test split','Precision','Recall','F1','Confusion matrix'],'Evaluation report'],
['Cross-validation',['Cross-validation','Overfitting','Underfitting','Model selection'],'Validated model comparison'],['Advanced retrieval',['Embedding experiments','Reranking','Retrieval evaluation'],'RAG evaluation notebook'],['Safe tool calling',['Function calling','Structured tools','Validation','Safe execution'],'Small tool-using workflow'],['Agent workflows',['Planning','Orchestration','Memory boundaries','Human approval'],'Reliable workflow agent'],['Production foundations',['Logging','Monitoring','Prompt versions','Docker'],'Observable local AI service'],['Responsible AI',['Privacy','PII','Prompt injection','Threat modeling'],'Safety review and mitigations'],['Capstone discovery',['Users','Requirements','Architecture','Evaluation criteria','Plan'],'Capstone proposal and implementation plan'],['Capstone & portfolio',['Implementation','Testing','Documentation','Screenshots','Demo','GitHub'],'Capstone release and one-page case study']]
export const roadmapWeeks:RoadmapWeek[]=roadmap.map(([title,topics,build],i)=>({week:i+1,month:Math.floor(i/4)+1,title,topics,completedTopics:[],build,buildDone:false,status:'Not started',notes:'',github:'',startDate:'',completionDate:''}))
